Certification\Module\Test\Entity\Test:
    properties:
        title:
            - NotBlank: ~
            - Length:
                max: 100
        time:
            - NotBlank: ~
            - Type: integer
        calculation:
            - NotBlank: ~
            - Type: integer

Certification\Module\Test\Dto\QuestionData:
    properties:
        title:
            - NotBlank: ~
        score:
            - NotBlank: ~
        answer_one:
            - NotBlank: ~
        answer_two:
            - NotBlank: ~
        answer_three:
            - NotBlank: ~
        answer_four:
            - NotBlank: ~

Certification\Module\Test\Dto\TestData:
    properties:
        title:
            - NotBlank: ~
        time:
            - NotBlank: ~
        calculation:
            - NotBlank: ~